@LibraryApi_HostAddress = http://localhost:5087

### Get all authors
GET {{LibraryApi_HostAddress}}/authors

### Create a new author
POST {{LibraryApi_HostAddress}}/authors
Content-Type: application/json

{
	"firstName": "Krešo",
	"lastName": "Krešić",
	"dateOfBirth": "1985-04-12",
	"biography": "Test author for API verification."
}

### Get an author by id
GET {{LibraryApi_HostAddress}}/authors/6

### Update an author by id
PUT {{LibraryApi_HostAddress}}/authors/2
Content-Type: application/json

{
	"firstName": "Mirko",
	"lastName": "Peric Updated",
	"dateOfBirth": "1985-04-12",
	"biography": "Updated biography for testing."
}

### Delete an author by id
DELETE {{LibraryApi_HostAddress}}/authors/5

### Genres

### Get all genres
GET {{LibraryApi_HostAddress}}/genres

### Create a new genre
POST {{LibraryApi_HostAddress}}/genres
Content-Type: application/json

{
	"name": "Sci-Fi"
}

### Get a genre by id
GET {{LibraryApi_HostAddress}}/genres/1